In [1]:
import numpy as np

In [2]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [3]:
profit = revenue - expenses

In [4]:
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [12]:
price_per_unit = np.array([1000,40,1200])
units_sold = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [13]:
np.dot(price_per_unit , units_sold)

array([32600, 46400, 59000])

In [14]:
revenue_in_usd = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
revenue_in_inr=revenue_in_usd*75

In [15]:
revenue_in_inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [16]:
flowers_price_pre_unit = np.array([20,30,15])
units_sold = np.array([[50,60,25],[10,13,5],[40,70,52]])

In [17]:
revenue_per_month = np.dot(flowers_price_pre_unit,units_sold)
revenue_per_month

array([1900, 2640, 1430])